-- ADCDA DB01 V01R002
CREATE DATABASE NUDB
  STOGROUP SG1DB2
  BUFFERPOOL BP0;
CREATE TABLESPACE STHING
  USING STOGROUP SG1DB2
    PRIQTY -1
    SECQTY -1
  BUFFERPOOL BP0
  CLOSE NO;
CREATE TABLE THING
(REF    BIGINT NOT NULL,
 NAME   VARCHAR(120) NOT NULL,
 ADDR   VARCHAR(250) NOT NULL WITH DEFAULT
) IN NUDB.STHING;
CREATE INDEX XTHING  
  ON TABLE THING (REF)
  USING STOGROUP SG1DB2
    PRIQTY -1
    SECQTY -1
  CLOSE YES
  BUFFERPOOL BP0;
COMMENT ON TABLE THING ('Some table or other');
